#!/bin/sh

. /etc/openwrt_release

uci -q get system.@imm_init[0] > "/dev/null" || uci -q add system imm_init > "/dev/null"

if ! uci -q get system.@imm_init[0].lang > "/dev/null"; then
	uci -q batch <<-EOF
		set luci.main.lang="auto"
		commit luci

		set system.@imm_init[0].lang="1"
		commit system
	EOF
fi

sed -i "/log-facility/d" "/etc/dnsmasq.conf"
echo "log-facility=/dev/null" >> "/etc/dnsmasq.conf"

ln -sf "/sbin/ip" "/usr/bin/ip"

# 抗断电: 开机自动 fsck 修复 overlay (check_fs=1), 防断电后分区只读卡死
# 注: 仅对 squashfs 镜像的可写 overlay 生效; 纯 ext4 root 镜像无法自我 fsck
uci -q get fstab.@global[0] > "/dev/null" || uci -q add fstab global > "/dev/null"
uci -q batch <<-EOF
	set fstab.@global[0].check_fs="1"
	commit fstab
EOF

case "$DISTRIB_TARGET" in
"bcm4908"/*|\
"bcm53xx"/*|\
"ramips/mt7621"|\
"x86"/*)
	if ! uci -q get system.@imm_init[0].packet_steering > "/dev/null"; then
	uci -q batch <<-EOF
		set network.globals="globals"
		set network.@globals[0].packet_steering="1"
		commit network

		set system.@imm_init[0].packet_steering="1"
		commit system
	EOF
	fi
	;;
esac

exit 0
